### ISSUE TITLE
Angels don't stop moving when being looked at.

### ISSUE THREAD

**Issue by theeUnicorns** [Swirtzly/Weeping-Angels#101]
Version: weeping-angels-37.jar
Forge Version: 14.23.5.2838

Angels don't stop when they are being looked at.

**Comment by Swirtzly** [comment]
This requires more information. I can't work with what you've given. I don't know what other mods you have installed, I don't know context. I don't know what forge version. I'm closing this issue and marking it as invalid. When you provide logs and a video of the issue at hand, I will reopen this. Provide the required items in the comments of this issue.
