### ISSUE TITLE
Crash when Starting with Weeping Angels

### ISSUE THREAD

**Issue by ScienceDrummer** [Swirtzly/Weeping-Angels#103]
I appear to crash with the most recent version of Weeping Angels. I tested it out and when removed, the game launches fine. These are the 2 crash reports that came with it.
[crash-2019-09-14_17.45.50-client.txt](https://github.com/Swirtzly/Weeping-Angels/files/3613881/crash-2019-09-14_17.45.50-client.txt)
[crash-2019-09-14_17.45.51-client.txt](https://github.com/Swirtzly/Weeping-Angels/files/3613882/crash-2019-09-14_17.45.51-client.txt)

**Comment by Swirtzly** [comment]
This is what I get for refactoring things, forgot to change something back manually, I'll fix this now and then release a new build

**Comment by ScienceDrummer** [comment]
Nice

**Comment by Swirtzly** [comment]
https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/2786723
