### ISSUE TITLE
Can't kill anything with version 42-44

### ISSUE THREAD

**Issue by DeadzombiesO5** [Swirtzly/Weeping-Angels#110]
I don't know if its a bug or something but i can't seem to be able to kill anything with the weeping angel mod version 42-44.

**Comment by Swirtzly** [comment]
You turned on Hardcore mode in the mods settings, which was broken in 44

It is now fixed in 45: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/2908639

**Comment by DeadzombiesO5** [comment]
thank you so much, you are the best.
